version: '2'

services:
  apache2:
    build: .
    ports:
     - "80:80"
     - "443:443"
    links:
     - galaxy

  galaxy:
    image: bgruening/galaxy-stable
    container_name: galaxy
    ports:
     - "8080:80"
     - "8022:22"
     - "8021:21"
     - "9002:9002"
     - "8800:8800"
    environment:
     - GALAXY_LOGGING=full
     - GALAXY_CONFIG_HOST=127.0.0.1
     - GALAXY_CONFIG_APACHE_XSENDFILE=True
     - GALAXY_CONFIG_USE_REMOTE_USER=True
     - GALAXY_CONFIG_REMOTE_USER_LOGOUT_HREF= https://galaxy-docker.fedcloud-tf.fedcloud.eu/Shibboleth.sso/Logout
     - GALAXY_CONFIG_ADMIN_USERS=025166931789a0f57793a6092726c2ad89387a4cc167e7c63c5d85fc91021d18@egi.eu
    volumes:
     - "/home/ubuntu/galaxy_storage/:/export/"
     - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
     - "./nginx/uwsgi.conf:/etc/nginx/conf.d/uwsgi.conf"
    privileged: true
