version: '2'

services:
  apache2:
    build: .
    container_name: apache2
    ports:
     - "80:80"
     - "443:443"
    links:
     - galaxy

  galaxy:
    image: bgruening/galaxy-stable
    container_name: galaxy
    ports:
     - "8080:80"
     - "8022:22"
     - "8021:21"
     - "9002:9002"
     - "8800:8800"
    environment:
     - GALAXY_LOGGING=full
     - DOCKER_PARENT=True
     #- GALAXY_CONFIG_HOST=127.0.0.1
     - GALAXY_CONFIG_HOST=0.0.0.0
     - GALAXY_CONFIG_APACHE_XSENDFILE=True
     - GALAXY_CONFIG_USE_REMOTE_USER=True
     - GALAXY_CONFIG_GALAXY_INFRASTRUCTURE_URL=https://galaxy-docker.fedcloud-tf.fedcloud.eu
     - GALAXY_CONFIG_GALAXY_INFRASTRUCTURE_WEB_PORT=443
     - GALAXY_CONFIG_TOOL_CONFIG_FILE=config/tool_conf.xml.sample,config/shed_tool_conf.xml.sample,/local_tools/tool_conf.xml
     - GALAXY_CONFIG_INTERACTIVE_ENVIRONMENT_PLUGINS_DIRECTORY=config/plugins/interactive_environments
     - GALAXY_CONFIG_REMOTE_USER_LOGOUT_HREF=https://galaxy-docker.fedcloud-tf.fedcloud.eu/Shibboleth.sso/Logout
     - GALAXY_CONFIG_ADMIN_USERS=025166931789a0f57793a6092726c2ad89387a4cc167e7c63c5d85fc91021d18@egi.eu, 529a87e5ce04cd5ddd7161734d02df0e2199a11452430803e714cb1309cc3907@egi.eu, bf7f0e957d7d0566dfb8f7070deceb1e83805e679f913daaf35b50751c893227@egi.eu
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock"
     - "/mnt/galaxy_storage:/export/"
     - "./local_tools:/local_tools/"
     - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
     - "./nginx/uwsgi.conf:/etc/nginx/conf.d/uwsgi.conf"
     - "./galaxy-config/jupyter.ini:/galaxy-central/config/plugins/interactive_environments/jupyter/config/jupyter.ini"
    privileged: true
